'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.7905
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class portalcfd_Home

    '''<summary>
    '''lnk1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnk1 As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''lnk2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnk2 As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''lnk3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnk3 As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''lnk4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnk4 As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''lnk10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnk10 As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''lnk9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnk9 As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''lnk8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnk8 As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''lnk5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnk5 As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''lnk6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnk6 As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''lnk11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnk11 As Global.System.Web.UI.WebControls.ImageButton
End Class
